### ISSUE TITLE
Just load the scripts in the background instead of using an HTML intermediary

### ISSUE THREAD

**Issue by with-a-k** [anathomical/ljjuggler#2]
I noticed last night that the manifest loads an HTML page, and then that HTML loads the under-the-hood JavaScript, rather than having the manifest load the scripts directly. Why is this?

**Comment by anathomical** [comment]
Short answer: there's no good reason to do it the way that it's done here.  If you can load the scripts in the manifest and still expose them to the HTML namespace so that you can attach things like click events, that's probably cleaner.  (I suspect that this is possible, but haven't really dug into Chrome Extension namespacing when loading your resources in the manifest.)

Longer answer: The current state of the code is a pretty big mess.  It's something that I find tends to happen in single-contributor projects that evolve and extend over time.  The longer one person works on a project without getting other peoples' eyes on the code, the more likely they are to take shortcuts and refactor things in non-optimal ways.  In this particular case, the JavaScript was originally written directly into the HTML templates rather than kept in separate files, and the refactor that pulled it out did so in the fastest way possible: cut the code into separate files and replace the code snippets in the HTML with file loads.  And then things were just left that way because it worked well enough.

If you wanted to fix it, I'd totally accept a pull request focused on making the code base cleaner.  Or, really, just about any pull request with enhancements.

**Comment by with-a-k** [comment]
After some research, it turns out that the current implementation is actually more or less what Chrome already does under the hood, so it should work exactly the same.

Unfortunately, adding new accounts is, at least for Dreamwidth, _not_ working exactly the same since it's not working at all anymore. I'm wondering whether their login process has changed.

**Comment by anathomical** [comment]
Interesting.  I just ran a test on my system, and I was able to add a Dreamwidth account without any issues.  I wonder if there's some weird interaction with another extension that you may have installed that's causing issues?
